from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,Http404
# Create your views here.
# takes a request and returns a response
# like controllers in mvc

from .models import Movie
# movie is a class in models.py, movie is an app attribute, movie should be imported if u want to use it in diffrent places
# i need more explanation on what needs to be imported, what needs to be called, what needs to be included and how, f.e. in urls .py

def index(request):
    movies=Movie.objects.all() #how did i know it is not models.Movie.all() and is called directly from Movie

    # Movie.objects.filter(year = 2015)
    # Movie.objects.get(id=1) #database abstraction api
    
    output = " ,".join([i.title for i in movies])
    # response= 'hi there!<br> response generated by HttpResponse in views<br><br>NEXT STEP: <br> map this to a URL<br><br>'+f'{output}'
    # return HttpResponse(response)
    
    # return render(request, 'index.html', {'movies':movies}) #instead of passing the name of the file itself, we shall give it a name multiple app's index.html will get mixed up
    
    return render(request, 'movies/index.html', {'movies':movies})
    
    # here we render 3 things->1- request, 2-html page located in templates, 3-and i donno why we need to render a list like that?would we not do it in our html?why here again?
# todo: render a html template here

    
def detail(request, movie_id):
    # try:  
    #     movie = Movie.objects.get(pk=movie_id)
    #     # return HttpResponse(movie_id)
    #     return render(request, 'movies/detail.html', {'movie':movie})
    # except Movie.DoesNotExist:
    #     raise Http404
    
    # using shortcut
    # get_object_or_404 should know what kind of model to work with
    movie = get_object_or_404(Movie,pk=movie_id)
        
# we have a shortcut for raising execptions