# Generated by Django 5.2.14 on 2026-06-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='daily_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='number_in_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
